### ISSUE TITLE
FEATURE: custom features per language

### ISSUE THREAD

**Issue by rfc2119** [pacollins/hugo-future-imperfect-slim#125]
# Feature Request

Coming from #120 , I wanted to assign a font AND other styling elements  to a language other than English, so that the generated HTML or CSS is different per language

## Solution

I do not know how to approach this, and if the feature is specific to the theme or Hugo in general,  but a simple CSS per language would ideally work

## Alternatives
An example of such styling elements is support for right-to-left languages. The [direction](https://developer.mozilla.org/en-US/docs/Web/CSS/direction) property for CSS or the [dir](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) global HTML attribute achieves this. What I ended up with is modifiying `static/css/add-on.css` to include:

```css
h1,
h2,
h3,
h4,
h5,
h6, p, a, del, mark, ul, li,  table, tr, td,{
  direction: rtl;
  letter-spacing: unset;
}
```
Obviously, this breaks any English content
