### ISSUE TITLE
HELP: Setting an image in blog

### ISSUE THREAD

**Issue by pratikjagrut** [pacollins/hugo-future-imperfect-slim#248]
I'm trying to set an image in a blog but it looks so blurry and weird and not so good.
Here's a screenshot of image positioning.

![blurrygit](https://user-images.githubusercontent.com/26519653/116498766-26094780-a8c8-11eb-9bac-dfb1a23fea81.png)

This is the blog post metadata or Idk what to call it
```
images:
  - src: "img/git/logo.png"
    alt: "git logo"
    stretch: "horizontal"
```
I've tried three stretch options I know of, horizontal, vertical and stretchH, nothing works.
I don't know what to do. 
Can someone help me out here?

**Comment by pacollins** [comment]
If "vertical" still made it pixelated, then the image is too low resolution.

**Comment by pacollins** [comment]
Actually, looking closer it is because it is transparent. We should add a
way to turn off blur for this use case. I'll do that this evening.

**Comment by pacollins** [comment]
@pratikjagrut - Sorry for the triple response. This exists but is not in the wiki yet. In the front matter of the post, put "removeBlur = true".

Try that.

**Comment by pratikjagrut** [comment]
Not happening, still getting blur image.
```
images:
  - src: "img/git/logo.png"
    alt: "git logo"
    stretch: "horizontal"
    removeBlur: true
```
