### ISSUE TITLE
BUG: Menu code doesn't follow Hugo docs

### ISSUE THREAD

**Issue by VincentTam** [pacollins/hugo-future-imperfect-slim#46]
# Code Change Request

## Is your request related to a problem?

The current code base makes use of the `identifier` field to render Font Awesome icons.
https://github.com/pacollins/hugo-future-imperfect-slim/blob/f0ec5ac57e6765ef2cf1cb4a2f585bfc1c1c5c6b/exampleSite/config.toml#L111-L115
Even though this works, this is not the intended role of this field.  This field serves as a unique ID for the menu entry so that its children be associate themselves with it using their `parent` field.

```toml
[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 1

[[menu.main]]
  name = "Math Resources"
  url = "math-live-preview"
  weight = 2

[[menu.main]]
  parent="Math Resources"
  name = "Math Editor"
  url = "math-live-preview"
  weight = 1

[[menu.main]]
  parent="Math Resources"
  name = "Math.SE Comments"
  url = "page/math-se-comment-templates/"
  weight = 2
```

Source: [site config](https://gitlab.com/VincentTam/vincenttam.gitlab.io/blob/3ba69921f1ed84e7d3fa878c99cf387e76d5b809/config.toml) for [my blog](https://vincenttam.gitlab.io)

## Solution

Use the `pre` field instead of `identifier`.

## Additional Context

- [Menu Entry Properties | Hugo](https://gohugo.io/variables/menus/#menu-entry-variables)
- [Menus | Hugo](https://gohugo.io/content-management/menus/)

**Comment by pacollins** [comment]
The only issue I see here is that it would prevent backwards compatibility with no way to do a work around.

**Comment by VincentTam** [comment]
> The only issue I see here is that it would prevent backwards compatibility with no way to do a work around.

@pacollins To substantialise your concern about backwards compatibility, here're [a list of Git repos that uses this theme](https://github.com/search?l=Git+Config&q=hugo-future-imperfect-slim&type=Code) as a submodule.

:thinking: Nonetheless, writing the theme in a way that's consistent with the Hugo docs makes it easier to be maintained and understood by other Hugo developers.

:bulb: After thinking about this for two hours, here's an idea that might satisfy both old and new users: *add some Hugo logic* on the config file to differentiate "old" and "new" users.

- old: keep using `identifier` for navbar icon
- new: do something like what I've done to my blog.
```go-html
{{ range .Site.Menus.main.ByWeight }}
  {{ if .HasChildren }}
    <li class="navlinks-container">
      {{ if .Pre }}
        <a class="navlinks-parent" title="{{ .Name }}">{{ .Pre }}</a>
      {{ else }}
        <a class="navlinks-parent">{{ .Name }}</a>
      {{ end }}
      <div class="navlinks-children">
        {{ range .Children }}
          {{ if .Pre }}
            <a title="{{ .Name }}" href="{{ .URL | relLangURL }}">{{ .Pre }}</a>
          {{ else }}
            <a href="{{ .URL  | relLangURL }}">{{ .Name }}</a>
          {{ end }}
        {{ end }}
      </div>
    </li>
  {{ else }}
    <li>
      {{ if .Pre }}
        <a title="{{ .Name }}" href="{{ .URL | relLangURL }}">{{ .Pre }}</a>
      {{ else }}
        <a href="{{ .URL | relLangURL }}">{{ .Name }}</a>
      {{ end }}
    </li>
  {{ end }}
{{ end }}
```
so that the following example in [Hugo's docs for Menus](https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu) would work.
```toml
[menu]

  [[menu.main]]
    identifier = "about"
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  [[menu.main]]
    name = "getting started"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/getting-started/"
    weight = -100
```
